<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM4zxx7R\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM4zxx7R/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM4zxx7R.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM4zxx7R\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM4zxx7R\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M4zxx7R',
    'container.build_id' => 'c523d00f',
    'container.build_time' => 1619398110,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM4zxx7R');
