<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Fspxx0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Fspxx0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3Fspxx0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3Fspxx0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3Fspxx0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3Fspxx0',
    'container.build_id' => '3311be17',
    'container.build_time' => 1619737640,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Fspxx0');
